service:
  name: ${self:custom.NAME}

frameworkVersion: ">=1.27.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: ${self:custom.STAGE}
  profile:   # awsのcredential名 複数持っていないなら記述不要

custom:
  NAME: nuxt-on-lambda
  STAGE: ${file(./configs/env.js):exporter.STAGE}
  BASE_URL: ${file(./configs/env.js):exporter.BASE_URL}
  ENDPOINT_ENV: ${file(./configs/env.js):exporter.ENDPOINT_ENV}

# 少しでもデプロイのパッケージファイルを少なくする
package:
  excludeDevDependencies: true
  exclude:
    - .**
    - .**/*
    - app/**
    - LICENSE
    - README.md
    - package.json
    - yarn.lock
    # Node.js 上で使われないモジュール
    # 重いものを優先的に除外
    - node_modules/babel**/**
    - node_modules/caniuse-db/**
    - node_modules/caniuse-lite/**
    - node_modules/prettier/**
    - node_modules/yargs/**
    - node_modules/postcss**/**
    - node_modules/cssnano/**
    - node_modules/sass-loader//**
    - node_modules/node-sass/**
    - node_modules/xxhashjs/**
    - node_modules/jschardet/**
    - node_modules/**/*.md
    - node_modules/**/bin/**
  include:
    - server/**
    - configs/**
    - nuxt.config.js
    - node_modules/postcss/**
    - node_modules/postcss-cssnext/**
    - node_modules/postcss-import/**
    - node_modules/postcss-import-resolver/**
    - node_modules/postcss-loader/**
    - node_modules/postcss-url/**


functions:
  handler:
    handler: server/handler.handler
    timeout: 30
    memorySize: 128
    environment:
      BASE_URL: ${self:custom.BASE_URL}
      ENDPOINT_ENV: ${self:custom.ENDPOINT_ENV}
    events:
      - http:
          path: '/'
          method: get
      - http:
          path: '{proxy+}'
          method: get

